# Root Module — WordPress on ECS
# Includes: VPC, ECR, Secrets, RDS, IAM, ALB, ECS modules.

data "aws_availability_zones" "available" {
  state = "available"
}

data "aws_caller_identity" "current" {}

locals {
  account_id = data.aws_caller_identity.current.account_id
  azs        = slice(data.aws_availability_zones.available.names, 0, 2)
  name_prefix = "${var.project_name}-${var.environment}"
}

# VPC - Networking, subnets, IGW, NAT Gateway, route tables

module "vpc" {
  source = "./modules/vpc"

  name_prefix          = local.name_prefix
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  availability_zones   = local.azs
}

# ECR — Container registry, and it needs to exist before Packer pushing the image

module "ecr" {
  source = "./modules/ecr"

  name_prefix  = local.name_prefix
  account_id   = local.account_id
}

# Secrets Manager — RDS credentials

module "secrets" {
  source = "./modules/secrets"

  name_prefix  = local.name_prefix
  db_name      = var.db_name
  db_username  = var.db_username
  db_host      = module.rds.address
  # Password generated by the secrets module using random_password
}

# RDS — MySQL database

module "rds" {
  source = "./modules/rds"

  name_prefix              = local.name_prefix
  vpc_id                   = module.vpc.vpc_id
  subnet_ids               = module.vpc.private_subnet_ids
  db_name                  = var.db_name
  db_username              = var.db_username
  db_password              = module.secrets.db_password
  db_instance_class        = var.db_instance_class
  db_allocated_storage     = var.db_allocated_storage
  db_multi_az              = var.db_multi_az
  db_backup_retention_days = var.db_backup_retention_days
  ecs_security_group_id    = module.ecs.task_security_group_id
}

# IAM — ECS task roles

module "iam" {
  source = "./modules/iam"

  name_prefix      = local.name_prefix
  account_id       = local.account_id
  aws_region       = var.aws_region
  ecr_repo_arn     = module.ecr.repository_arn
  secret_arns      = [module.secrets.secret_arn]
}

# ALB — Application Load Balancer

module "alb" {
  source = "./modules/alb"

  name_prefix       = local.name_prefix
  vpc_id            = module.vpc.vpc_id
  public_subnet_ids = module.vpc.public_subnet_ids
}

# ECS — Container orchestration, and the main module tying everything together

module "ecs" {
  source = "./modules/ecs"

  name_prefix              = local.name_prefix
  aws_region               = var.aws_region
  vpc_id                   = module.vpc.vpc_id
  private_subnet_ids       = module.vpc.private_subnet_ids
  alb_security_group_id    = module.alb.security_group_id
  alb_target_group_arn     = module.alb.target_group_arn
  task_execution_role_arn  = module.iam.task_execution_role_arn
  task_role_arn            = module.iam.task_role_arn
  ecr_image_url            = "${module.ecr.repository_url}:${var.wordpress_image_tag}"
  ecs_task_cpu             = var.ecs_task_cpu
  ecs_task_memory          = var.ecs_task_memory
  ecs_desired_count        = var.ecs_desired_count
  ecs_min_capacity         = var.ecs_min_capacity
  ecs_max_capacity         = var.ecs_max_capacity
  secret_arn               = module.secrets.secret_arn
  db_host                  = module.rds.address
  wordpress_debug          = var.wordpress_debug
  wordpress_force_ssl      = var.wordpress_force_ssl
}